name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        username: ${{DOCKER_ID}}
        password: ${{DOCKER_PWD}}
    - name: Build the Docker image
      run: docker build -t ${{DOCKER_ID}}/cloudenginelabs:1.0${{GITHUB_RUN_ID}} .

    - name: Push Docker Image
      run: docker push ${{DOCKER_ID}}/cloudenginelabs:1.0${{GITHUB_RUN_ID}}
